import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(path,deps={},env={}){const exports={};const source=readFileSync(new URL(`../src/${path}`,import.meta.url),'utf8');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;vm.runInNewContext(compiled,{exports,require:id=>{if(id in deps)return deps[id];throw new Error(`Unmocked dependency ${id}`);},process:{env},URL,Response,Request,AbortSignal,Buffer,console,fetch:()=>{throw new Error('Live network is forbidden in report tests');}});return exports;}
const fmt=load('lib/reports/milestoneFormat.ts');
test('report links allow only local UUID report continuations',()=>{const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';assert.equal(fmt.safeReportReturn(`/reports/${id}`),`/reports/${id}`);for(const value of ['https://evil.test','//evil.test','/reports/..%2Fadmin','/reports/not-id','/reports/'+id+'?next=https://evil.test'])assert.equal(fmt.safeReportReturn(value),null);});
test('goals preserve actual above optimum and distinguish null from zero',()=>{assert.equal(fmt.activityGoal({actual:300,minimum:52,optimum:108}).fill,1);assert.equal(fmt.activityGoal({actual:67,minimum:52,optimum:108}).status,'Minimum reached');assert.equal(fmt.activityGoal({actual:null,minimum:52,optimum:108}).status,'Not available');assert.equal(fmt.activityGoal({actual:0,minimum:0,optimum:0}).status,'No activity recorded');assert.equal(fmt.activityGoal({actual:9,minimum:9,optimum:9}).single,true);});
test('timestamp dates respect Edmonton near midnight, period dates remain exact',()=>{assert.equal(fmt.reportTimestamp('2026-08-31T03:00:00Z','America/Edmonton'),'Aug 30, 2026');assert.equal(fmt.reportDate('2026-08-31'),'Aug 31, 2026');});
const env={GHL_PRIVATE_INTEGRATION_TOKEN:'test-only',GHL_LOCATION_ID:'test-location',GHL_EMAIL_FROM:'test@example.test'};
const email=load('lib/reports/reportEmail.ts',{'./milestoneFormat':fmt},env);
const snapshot={id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',milestone:'day30',member_name:'<script> & Test',period_start:'2026-01-01',period_end:'2026-01-30'};
test('email includes authenticated link and escapes member names',()=>{const result=email.reportEmail(snapshot,'https://reports.example.test');assert.match(result.html,/https:\/\/reports.example.test\/reports\/aaaaaaaa/);assert.ok(!result.html.includes('<script>'));assert.match(result.html,/&lt;script&gt;/);assert.throws(()=>email.reportEmail(snapshot,'http://example.test'));assert.throws(()=>email.reportEmail(snapshot,'https://user:pass@example.test'));});
const emailInput={email:'member@example.test',name:'Synthetic Member',html:'<p>Test</p>',subject:'Test'};
test('unknown final POST response is never automatically retried',async()=>{let calls=0;const request=async()=>{calls++;if(calls===1)return Response.json({contact:{id:'contact'}});throw new Error('Timed out after sending');};await assert.rejects(email.sendReportEmail(emailInput,request),e=>e.outcome==='unknown');assert.equal(calls,2);});
test('provider rejection is failed, successful missing ID is unknown',async()=>{for(const [response,outcome]of [[new Response('{}',{status:400}),'failed'],[Response.json({}),'unknown'],[new Response('{}',{status:503}),'unknown']]){let calls=0;await assert.rejects(email.sendReportEmail(emailInput,async()=>++calls===1?Response.json({contact:{id:'contact'}}):response),e=>e.outcome===outcome);assert.equal(calls,2);}});
test('successful final send records provider ID once',async()=>{let calls=0;const id=await email.sendReportEmail(emailInput,async()=>++calls===1?Response.json({contact:{id:'contact'}}):Response.json({messageId:'provider-123'}));assert.equal(id,'provider-123');assert.equal(calls,2);});
test('failed contact preparation never sends an email',async()=>{let calls=0;await assert.rejects(email.sendReportEmail(emailInput,async()=>{calls++;return new Response('{}',{status:500});}),e=>e.outcome==='failed');assert.equal(calls,1);});
function route({auth=null,rpcData=null,rpcError=null}={},pdf=false){const calls=[];const client={rpc:async(...args)=>{calls.push(args);return {data:rpcData,error:rpcError};}};const helpers={reportAuthorization:async()=>auth,reportClient:()=>client,reportRevision:url=>{const raw=new URL(url).searchParams.get('revision');if(raw!==null&&!/^[1-9]\d{0,6}$/.test(raw))throw new Error();return raw===null?null:Number(raw);},privateHeaders:{'Cache-Control':'private, no-store'}};const deps={'next/server':{NextResponse:{json:(body,options)=>new Response(JSON.stringify(body),options)}},'@/lib/reports/access':helpers,'@/lib/exports/adminClient':{supabaseAdmin:client},'@/lib/reports/milestoneFormat':fmt,'@/lib/reports/milestonePdf':{generateMilestonePdf:async()=>Buffer.from('%PDF-1.4 synthetic')}};return {api:load(`app/api/reports/[id]/${pdf?'pdf/':''}route.ts`,deps),calls};}
const reportId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';const params={params:Promise.resolve({id:reportId})};
test('unauthenticated JSON and PDF requests cannot reach database',async()=>{for(const pdf of [false,true]){const result=route({},pdf);assert.equal((await result.api.GET(new Request('https://example.test'),params)).status,401);assert.equal(result.calls.length,0);}});
test('members and admins use distinct RPCs and exact requested revision',async()=>{for(const admin of [false,true]){const result=route({auth:{token:'test',admin},rpcData:{id:reportId,revision:2}});const response=await result.api.GET(new Request('https://example.test?revision=2'),params);assert.equal(response.status,200);assert.equal(result.calls[0][0],admin?'admin_get_member_report':'get_member_report');assert.equal(result.calls[0][1]._revision,2);assert.equal(response.headers.get('cache-control'),'private, no-store');}});
test('foreign reports and invalid revisions do not leak records',async()=>{const result=route({auth:{token:'test',admin:false}});assert.equal((await result.api.GET(new Request('https://example.test'),params)).status,404);const invalid=route({auth:{token:'test',admin:false}});assert.equal((await invalid.api.GET(new Request('https://example.test?revision=-2'),params)).status,400);assert.equal(invalid.calls.length,0);});
test('PDF response uses stored revision in download name and private caching',async()=>{const result=route({auth:{token:'test',admin:false},rpcData:{id:reportId,revision:3,milestone:'day30',period_end:'2026-08-30'}},true);const response=await result.api.GET(new Request('https://example.test?revision=3'),params);assert.equal(response.headers.get('content-type'),'application/pdf');assert.match(response.headers.get('content-disposition'),/v3.pdf/);assert.equal(result.calls[0][1]._revision,3);});
test('worker leaves sends disabled unless explicitly enabled',async()=>{const calls=[];const client={rpc:async name=>{calls.push(name);return {data:0,error:null};}};const worker=load('lib/reports/reportWorker.ts',{'@/lib/exports/adminClient':{supabaseAdmin:client},'./reportEmail':email},{});await worker.runReportJob();assert.deepEqual(calls,['generate_due_member_reports']);});
test('worker acknowledges uncertain delivery without retrying',async()=>{const calls=[];const client={rpc:async(name,args)=>{calls.push([name,args]);return {data:name==='claim_member_report_email'?[{delivery_id:'d',claim_token:'c',user_id:'u',snapshot:{...snapshot,member_name:'Test'}}]:0,error:null};},auth:{admin:{getUserById:async()=>({data:{user:{email:'test@example.test'}},error:null})}}};const worker=load('lib/reports/reportWorker.ts',{'@/lib/exports/adminClient':{supabaseAdmin:client},'./reportEmail':{...email,sendReportEmail:async()=>{throw new email.ReportEmailFailure('Uncertain','unknown');}}},{...env,REPORTS_SITE_URL:'https://reports.example.test',REPORTS_EMAIL_ENABLED:'true'});const result=await worker.runReportJob();assert.equal(result.deliveries[0].status,'unknown');assert.equal(calls.at(-1)[1]._outcome,'unknown');assert.equal(calls.filter(([name])=>name==='claim_member_report_email').length,1);});

function pageHarness(){
 const source=readFileSync(new URL('../src/app/reports/[id]/page.tsx',import.meta.url),'utf8');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 const state=[],refs=[],effects=[],requests=[];let index=0,refIndex=0,listener;const exports={};const session={user:{id:'owner-a'},access_token:'token-a'};
 const react={useState:initial=>{const i=index++;state[i]=initial;return [state[i],value=>{state[i]=value;}];},useRef:value=>refs[refIndex++]={current:value},useEffect:effect=>effects.push(effect)};
 const deps={'react':react,'react/jsx-runtime':{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})},'next/navigation':{useParams:()=>({id:reportId}),useRouter:()=>({replace:()=>{}})},'@/lib/supabaseClient':{supabase:{auth:{getSession:async()=>({data:{session}}),onAuthStateChange:callback=>{listener=callback;return {data:{subscription:{unsubscribe(){}}}};}},rpc:async()=>({data:null,error:null})}},'@/lib/reports/milestoneFormat':fmt,'@/components/MilestoneReport':{default:()=>null}};
 vm.runInNewContext(compiled,{exports,require:id=>deps[id],fetch:(_url,options)=>new Promise(resolve=>requests.push({resolve,options})),AbortController,URL,console,setTimeout});exports.default();const cleanup=effects[0]();return {state,requests,emit:newSession=>listener(newSession?'SIGNED_IN':'SIGNED_OUT',newSession),cleanup};
}
const settle=async()=>{await new Promise(resolve=>setImmediate(resolve));};
test('a late report response cannot reappear after sign-out',async()=>{const page=pageHarness();await settle();assert.equal(page.requests.length,1);page.emit(null);assert.equal(page.requests[0].options.signal.aborted,true);page.requests[0].resolve(Response.json({report:{user_id:'owner-a'}}));await settle();assert.equal(page.state[0],null);page.cleanup();});
test('an account switch clears the old report and ignores its pending response',async()=>{const page=pageHarness();await settle();page.emit({user:{id:'owner-b'},access_token:'token-b'});assert.equal(page.requests.length,2);page.requests[0].resolve(Response.json({report:{user_id:'owner-a'}}));await settle();assert.equal(page.state[0],null);page.requests[1].resolve(Response.json({report:{user_id:'owner-b'}}));await settle();assert.equal(page.state[0].user_id,'owner-b');page.cleanup();});
