 'use client';
import {useCallback,useEffect,useState} from 'react';
import {Alert,Box,Button,Checkbox,Dialog,DialogContent,DialogActions,FormControlLabel,MenuItem,TextField,Typography} from '@mui/material';
import {supabase} from '@/lib/supabaseClient';
import MilestoneReport from './MilestoneReport';
import type {ReportSnapshot} from '@/lib/reports/reportTypes';
import {reportDate,reportTitle} from '@/lib/reports/milestoneFormat';
type Entry={report:ReportSnapshot;delivery:{id:string;status:string;attempt:number;provider_id:string|null;error:string|null;updated_at:string}|null};
type Member={id:string;first_name?:string;last_name?:string;email?:string};type Course={course_id:string;course_name:string};
export default function ReportCardsAdmin({users,courses}:{users:Member[];courses:Course[]}){
 const [entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[member,setMember]=useState(''),[course,setCourse]=useState(''),[milestone,setMilestone]=useState('day30'),[preview,setPreview]=useState<ReportSnapshot|null>(null),[action,setAction]=useState<{kind:'regenerate'|'resend';entry:Entry}|null>(null),[reason,setReason]=useState(''),[acknowledged,setAcknowledged]=useState(false);
 const api=useCallback(async(body?:Record<string,unknown>)=>{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Please sign in again.');const response=await fetch('/api/superadmin/reports',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Report request failed.');return result;},[]);
 const load=useCallback(async()=>{try{const result=await api();setEntries(result.reports);}catch(err){setError(err instanceof Error?err.message:'Reports could not load.');}},[api]);useEffect(()=>{void load();},[load]);
 async function previewReport(){setBusy(true);setError('');try{const result=await api({action:'preview',user_id:member,course_id:course,milestone});setPreview(result.result);}catch(err){setError(err instanceof Error?err.message:'Preview failed.');}finally{setBusy(false);}}
 async function perform(){if(!action)return;setBusy(true);setError('');try{await api({action:action.kind,report_id:action.entry.report.id,reason,acknowledge_unknown:acknowledged});setMessage(action.kind==='regenerate'?'Updated report saved. Previous versions are preserved.':'Notification queued. The next enabled delivery job will send it.');setAction(null);await load();}catch(err){setError(err instanceof Error?err.message:'Action failed.');}finally{setBusy(false);}}
 return <Box><Typography variant="h5" fontWeight={700}>Report cards</Typography><Typography color="text.secondary" sx={{mt:1,mb:3}}>Preview completed milestones, review saved reports, and manage corrections or email delivery.</Typography>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{message&&<Alert severity="success" sx={{mb:2}} onClose={()=>setMessage('')}>{message}</Alert>}
 <Box sx={{display:'flex',gap:2,flexWrap:'wrap',alignItems:'center',pb:3,borderBottom:'1px solid #ddd'}}><TextField select label="Member" value={member} onChange={e=>setMember(e.target.value)} size="small" sx={{minWidth:220}}>{users.map(user=><MenuItem key={user.id} value={user.id}>{[user.first_name,user.last_name].filter(Boolean).join(' ')||user.email||'Unnamed member'}</MenuItem>)}</TextField><TextField select label="Course" value={course} onChange={e=>setCourse(e.target.value)} size="small" sx={{minWidth:200}}>{courses.map(item=><MenuItem key={item.course_id} value={item.course_id}>{item.course_name}</MenuItem>)}</TextField><TextField select label="Milestone" value={milestone} onChange={e=>setMilestone(e.target.value)} size="small" sx={{minWidth:150}}><MenuItem value="day30">30-day</MenuItem><MenuItem value="day60">60-day</MenuItem><MenuItem value="final">Final</MenuItem></TextField><Button onClick={previewReport} disabled={busy||!member||!course} variant="outlined">Preview report</Button></Box>
 <Typography sx={{mt:3,mb:1}} variant="h6">Recent saved reports</Typography>{!entries.length&&<Typography sx={{py:3}} color="text.secondary">Saved reports will appear here after report generation is enabled.</Typography>}{entries.map(entry=><Box key={entry.report.id} sx={{py:2,borderBottom:'1px solid #ddd',display:'flex',gap:2,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><Box><Typography fontWeight={700}>{entry.report.member_name} · {reportTitle(entry.report.milestone)}</Typography><Typography variant="body2" color="text.secondary">{entry.report.course_name} · Through {reportDate(entry.report.period_end)} · Version {entry.report.revision}</Typography><Typography variant="body2">Email: {entry.delivery?.status||'Not queued'}{entry.delivery?.error?` · ${entry.delivery.error}`:''}</Typography></Box><Box sx={{display:'flex',gap:1,flexWrap:'wrap'}}><Button onClick={()=>setPreview(entry.report)}>View</Button><Button disabled={busy} onClick={()=>{setAction({kind:'regenerate',entry});setReason('');}}>Correct report</Button><Button disabled={busy||entry.delivery?.status==='sending'||entry.delivery?.status==='pending'} onClick={()=>{setAction({kind:'resend',entry});setAcknowledged(false);}}>Resend email</Button></Box></Box>)}
 <Dialog open={!!preview} onClose={()=>setPreview(null)} maxWidth="md" fullWidth><DialogContent sx={{p:0}}>{preview&&<MilestoneReport report={preview}/>}</DialogContent><DialogActions>{preview&&preview.revision>0&&<Button href={`/reports/${preview.id}`} target="_blank">Open report / PDF</Button>}<Button onClick={()=>setPreview(null)}>Close</Button></DialogActions></Dialog>
 <Dialog open={!!action} onClose={()=>!busy&&setAction(null)} maxWidth="sm" fullWidth><DialogContent>{action?.kind==='regenerate'?<><Typography variant="h6">Save a corrected report</Typography><Typography sx={{my:2}}>Recalculate the recorded activity and achievements. The earlier version stays saved, and no new email is sent automatically.</Typography><TextField fullWidth multiline minRows={2} label="Reason for correction" value={reason} onChange={e=>setReason(e.target.value)} inputProps={{maxLength:500}}/></>:<><Typography variant="h6">Send another report notification</Typography><Typography sx={{mt:2}}>This queues another email for {action?.entry.report.member_name}. It does not change their report.</Typography>{action?.entry.delivery?.status==='unknown'&&<><Alert severity="warning" sx={{mt:2}}>The previous send may have succeeded. Check its status in GoHighLevel before retrying.</Alert><FormControlLabel control={<Checkbox checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/>} label="I checked the previous send and want to send another email."/></>}</>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setAction(null)}>Cancel</Button><Button variant="contained" onClick={perform} disabled={busy||(action?.kind==='regenerate'&&reason.trim().length<5)||(action?.kind==='resend'&&action.entry.delivery?.status==='unknown'&&!acknowledged)}>{busy?'Saving…':action?.kind==='regenerate'?'Save corrected version':'Queue email'}</Button></DialogActions></Dialog>
 </Box>;
}
